server:
  port: 9898

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: karol
    password: Zoey@1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true